/* Autogenerated, don't edit */

#define SCST_INTF_VER "e1df70ef5ed0fdb0194fcf5d1a466a3270074347"
#define SCST_CONST_INTF_VER "804884cc1c3ece0056e7f4f92fd9b8b922bf6354"
#define DEV_USER_INTF_VER "bab23b70314abb59edd4bfe507477e42b4190eb4"
