/* Autogenerated, don't edit */

#define SCST_INTF_VER "85ba1a7a31c39f4c1cb8b492cc7794f7f79156df"
#define SCST_CONST_INTF_VER "5522fdd24545344fca2fa11c64e2eaa15ecb2c17"
#define DEV_USER_INTF_VER "48325ce6b0075b0fa4f25cbdab2962a80b7f6487"
